.TH ROSE_CALL 8 "11 December 1996" Linux "Linux Programmer's Manual"
.SH NAME
rose_call \- make a ROSE connection
.SH SYNOPSIS
.B rose_call port local_call remote_call remote_rose_addr
.SH DESCRIPTION
.LP
.B rose_call
establishes a ROSE connection in a manner suitable for calling from either
the
.B ax25d
program directly, or from the
.B node
program as an external command. By setting the command line arguments
appropriately it is possible to set the local callsign from which the call
will be made. No translation of the end of line conventions is performed by
this program.
.sp 1
The remote_rose_addr parameter must be in the form of a ten digit ROSE address.
.SH FILES
.br
/etc/ax25/rsports
.SH "SEE ALSO"
.BR rose (4).
.SH AUTHOR
Jonathan Naylor G4KLX <g4klx@g4klx.demon.co.uk>
